server:
  port: 9098

spring:
  data:
    mongodb:
      uri: *****************************************************

  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 100MB

